Repository WoodenTucker/Blue-Colony-Reborn, pull requests merged in 2023-10, with the labels that each got.

#100 Crew Transfer Shuttle Fix
  maps/geminus_kiel/geminus_neue-1.dmm
  maps/geminus_kiel/geminus_neue-2.dmm
  maps/geminus_kiel/geminus_neue-4.dmm
Labels: Bugfix, Mapping

#101 Governor office overhaul
  maps/geminus_kiel/geminus_neue-3.dmm
Labels: Mapping

#106 Fixes seveal things in the art system, and adds a bit more features.
  code/game/objects/structures/artstuff.dm
Labels: QoL/Enhancement, Coding

#108 map changes
  maps/geminus_kiel/geminus_neue-2.dmm
  maps/geminus_kiel/geminus_neue-3.dmm
  maps/geminus_kiel/geminus_neue_lot_areas.dm
  maps/geminus_kiel/geminus_neue_lots.dm
Labels: Mapping, Coding

#107 Rearranges police equipemnt so communicator correctly spawns.
  code/datums/outfits/jobs/security.dm
Labels: Bugfix, Coding

#109 City Hall 2nd Floor Disposals & Edits
  maps/geminus_kiel/geminus_neue-2.dmm
  maps/geminus_kiel/geminus_neue-3.dmm
Labels: Mapping

#111 Removal of Unnecessary geminus_neue.dm
  polaris.dme
Labels: Coding

#113 NO MORE LEWD BORGS
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
Labels: Spriting, Coding

#114 PD Persistent Evidence Storage
  code/game/turfs/flooring/flooring_decals.dm
  icons/turf/flooring/decals.dmi
  maps/geminus_kiel/geminus_neue-2.dmm
  maps/geminus_kiel/geminus_neue-3.dmm
  maps/geminus_kiel/geminus_neue_lot_areas.dm
  maps/geminus_kiel/geminus_neue_lots.dm
Labels: Mapping

#115 PD Persistent Evidence Storage IDs
  icons/turf/flooring/decals.dmi
  maps/geminus_kiel/geminus_neue_lot_areas.dm
  maps/geminus_kiel/geminus_neue_lots.dm
Labels: Spriting, Coding

#116 persistence
  maps/geminus_kiel/geminus_neue-2.dmm
Labels: Mapping

#117 police hats
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/clothing/head/jobs.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
  maps/geminus_kiel/geminus_neue-3.dmm
Labels: Spriting

#119 Camera Overhaul & Minor Map Additions
  code/game/turfs/flooring/flooring_decals.dm
  icons/turf/flooring/decals.dmi
  maps/geminus_kiel/geminus_neue-1.dmm
  maps/geminus_kiel/geminus_neue-2.dmm
  maps/geminus_kiel/geminus_neue-3.dmm
Labels: QoL/Enhancement, Mapping, Spriting

#120 Time for the world to change...
  code/__defines/planets.dm
  code/datums/uplink/announcements.dm
  code/modules/events/event_container.dm
  code/modules/events/event_dynamic.dm
  code/modules/mob/living/simple_animal/animals/giant_spider/corroder.dm
  code/modules/mob/living/simple_animal/animals/giant_spider/mindweaver.dm
  code/modules/mob/living/simple_animal/animals/giant_spider/spitter.dm
  code/modules/planet/pollux.dm
  code/modules/projectiles/projectile/energy.dm
  icons/mob/animal.dmi
  icons/obj/projectiles.dmi
  polaris.dme
Labels: QoL/Enhancement, Coding

#121 Camera Fixes
  maps/geminus_kiel/geminus_neue-2.dmm
  maps/geminus_kiel/geminus_neue-3.dmm
Labels: Mapping

#126 Fixed airlocks keeping their entered code when 'lock' is pressed
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/windowdoor.dm
Labels: QoL/Enhancement, Bugfix

#125 multitool
  icons/obj/abductor.dmi
Labels: Bugfix, Spriting

#123 Update council.dm
  code/game/jobs/job/council.dm
Labels: QoL/Enhancement
