Repository WoodenTucker/Blue-Colony-Reborn, pull requests merged in 2023-11, with the labels that each got.

#129 Edits and changes
  code/modules/mob/living/simple_animal/animals/giant_spider/corroder.dm
  code/modules/mob/living/simple_animal/animals/giant_spider/spitter.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  icons/mob/animal.dmi
  maps/geminus_kiel/geminus_neue-1.dmm
  maps/geminus_kiel/geminus_neue-2.dmm
  maps/geminus_kiel/geminus_neue-3.dmm
  maps/geminus_kiel/geminus_neue_defines.dm
Labels: Bugfix, Mapping, Spriting

#128 governor overhaul
  code/datums/outfits/jobs/nanotrasen.dm
  code/game/jobs/access_datum.dm
  code/game/jobs/job/nanotrasen.dm
  code/game/jobs/jobs.dm
  code/game/objects/items/weapons/id cards/station_ids.dm
  code/modules/government/president/cabinet.dm
  code/modules/government/president/communications.dm
  config/hardwhitelist.txt
  maps/geminus_kiel/geminus_neue-2.dmm
  maps/geminus_kiel/geminus_neue-3.dmm
Labels: Coding

#130 General
  code/modules/projectiles/guns/energy/special.dm
  code/modules/research/designs.dm
  config/hardwhitelist.txt
Labels: QoL/Enhancement

#133 mapchanges 2 (I'm sexually inactive)
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/semiauto.dm
  config/hardwhitelist.txt
  maps/geminus_kiel/geminus_neue-2.dmm
  maps/geminus_kiel/geminus_neue-3.dmm
Labels: Mapping

#137 City Hall Archive
  maps/geminus_kiel/geminus_neue-3.dmm
  maps/geminus_kiel/geminus_neue_areas.dm
  maps/geminus_kiel/geminus_neue_lot_areas.dm
  maps/geminus_kiel/geminus_neue_lots.dm
Labels: Mapping

#138 Added feedback to the code
  code/game/mecha/mech_fabricator.dm
  code/game/mecha/mech_prosthetics.dm
Labels: QoL/Enhancement
